### ISSUE TITLE
Crediting DSG

### ISSUE THREAD

**Issue by PatrickYott** [NEU-DSG/ECDA#1]
Please add DSG to where the project is credited.  
Something like..

ECDA is a project of the NULab for texts, maps, and networks and the Digital Scholarship Group at Northeastern University.

**Comment by dhscratch** [comment]
@PatrickYott if you mean in git, can you point me to an example of how projects in DSG are representing partnerships/supporters in git? I'm just now adding project data/content into our git space, so any advice/models you may have, I'd really appreciate the guidance. If you mean on the ecda project site, dsg is listed in a few places as a primary supporter.
